---
- name: Clusters_Info playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: 192.168.100.19
      nutanix_username: admin
      nutanix_password: Hitachi#1234
      validate_certs: false

  tasks:
  - name: List all Protection rules
    ntnx_protection_rules_info:
    register: result

